# Create & update a latest tag pointing to your latest release
# Then publish to PyPI with this latest release
name: Release

on:
  workflow_dispatch:
  release:
    types:
      - "published"

permissions:
  id-token: write
  contents: read

jobs:
  sdist:
    if: startsWith(github.ref, 'refs/tags')
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          pip install -U pip setuptools build
      - name: Clean remaining artifacts
        run: |
          make clean
      - name: Build source distribution
        run: |
          python -m build --sdist
      - name: Upload source distribution as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: dist/

  wheels:
    needs: sdist
    name: Build wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Clean remaining artifacts
        run: |
          make clean
      - name: Install dependencies
        run: |
          pip install -U pip build wheel
      - name: Build package
        run: |
          python -m build --wheel --outdir wheelhouse
      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse/

  publish:
    needs: [sdist, wheels]
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download source distribution as artifact
        uses: actions/download-artifact@v3
        with:
          name: sdist
          path: dist/
      - name: Download wheels as artifacts
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
